# Generated by Django 5.2.5 on 2026-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_veterinarianprofile_rating_count_veterinarianreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PET_OWNER', 'Pet Owner'), ('VETERINARIAN', 'Veterinarian'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], db_index=True, default='PET_OWNER', max_length=20),
        ),
    ]
