# Generated by Django 5.2.5 on 2026-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarianprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
