# Generated by Django 5.2.5 on 2026-08-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_veterinarianprofile_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
