# Generated by Django 5.2.15 on 2026-06-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_chk_duration_valid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='chk_scheduled_future',
        ),
    ]
