# Generated by Django 5.2.15 on 2026-06-16 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('APPOINTMENT_CREATED', 'Appointment Created'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_STARTED', 'Appointment Started'), ('APPOINTMENT_COMPLETED', 'Appointment Completed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('REVIEW_RECEIVED', 'Review Received'), ('GENERAL', 'General Notification')], db_index=True, default='GENERAL', max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('related_type', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
