# Generated by Django 5.2.5 on 2026-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_CREATED', 'Appointment Created'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_STARTED', 'Appointment Started'), ('APPOINTMENT_COMPLETED', 'Appointment Completed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('REVIEW_RECEIVED', 'Review Received'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_PAYMENT_SUCCESS', 'Order Payment Success'), ('SELLER_NEW_ORDER', 'Seller New Order'), ('SELLER_LOW_STOCK', 'Seller Low Stock'), ('SELLER_NEW_REVIEW', 'Seller New Review'), ('ADMIN_NEW_SELLER', 'Admin New Seller'), ('ADMIN_PRODUCT_PENDING', 'Admin Product Pending'), ('ADMIN_REFUND_REQUEST', 'Admin Refund Request'), ('GENERAL', 'General Notification')], db_index=True, default='GENERAL', max_length=50),
        ),
    ]
