# Generated by Django 5.2.15 on 2026-06-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("APPOINTMENT_CREATED", "Appointment Created"),
                    ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                    ("APPOINTMENT_STARTED", "Appointment Started"),
                    ("APPOINTMENT_COMPLETED", "Appointment Completed"),
                    ("PAYMENT_RECEIVED", "Payment Received"),
                    ("REVIEW_RECEIVED", "Review Received"),
                    ("GENERAL", "General Notification"),
                ],
                db_index=True,
                default="GENERAL",
                max_length=50,
            ),
        ),
    ]
