# Generated by Django 5.2.5 on 2026-06-17 07:48

from django.db import migrations
import uuid


def create_community_group(apps, schema_editor):
    """Create the default PetXpert Community group."""
    ChatGroup = apps.get_model('chat', 'ChatGroup')
    
    # Check if the community group already exists
    if not ChatGroup.objects.filter(name='PetXpert Community').exists():
        ChatGroup.objects.create(
            id=uuid.UUID('12345678-1234-5678-1234-567812345678'),  # Fixed UUID for consistency
            name='PetXpert Community',
            description='The official PetXpert community chat for pet owners and veterinarians',
            is_active=True
        )


def reverse_community_group(apps, schema_editor):
    """Reverse the migration - delete the community group."""
    ChatGroup = apps.get_model('chat', 'ChatGroup')
    ChatGroup.objects.filter(name='PetXpert Community').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_community_group, reverse_community_group),
    ]
